# Generated by Django 2.0.4 on 2019-07-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo_field1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FooBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_field', models.CharField(max_length=50)),
                ('foo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.Foo')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_field1', models.CharField(max_length=50)),
                ('m2mfield', models.ManyToManyField(through='trash.FooBar', to='trash.Foo')),
            ],
        ),
        migrations.AddField(
            model_name='foobar',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trash.Main'),
        ),
    ]
