# Generated by Django 2.2.3 on 2019-07-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='foo_field1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foobar',
            name='foo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.Foo'),
        ),
        migrations.AlterField(
            model_name='foobar',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trash.Main'),
        ),
        migrations.AlterField(
            model_name='foobar',
            name='new_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='m2mfield',
            field=models.ManyToManyField(null=True, through='trash.FooBar', to='trash.Foo'),
        ),
        migrations.AlterField(
            model_name='main',
            name='main_field1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
