# Generated by Django 2.2.3 on 2019-07-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_auto_20190730_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='m2mfield',
            field=models.ManyToManyField(to='trash.Foo'),
        ),
    ]
