# Generated by Django 2.2 on 2020-01-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_author_author2_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Author2',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
