# Generated by Django 2.0.2 on 2018-03-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180306_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
