# Generated by Django 2.0.4 on 2019-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
