# Generated by Django 2.0.4 on 2019-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.NullBooleanField(default=False),
        ),
    ]
