# Generated by Django 2.0.4 on 2019-07-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_active'),
        ('books', '0004_book_is_available'),
    ]

    operations = [
    ]
