# Generated by Django 2.2.4 on 2019-09-13 13:24

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                # 'constraints': [],
            },
            bases=('books.books',),
        ),
        migrations.AddField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
