# Generated by Django 2.2.4 on 2019-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20190913_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
