# Generated by Django 2.2.4 on 2019-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_book_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
