# Generated by Django 2.0.4 on 2020-01-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20191213_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dob',
            field=models.DateField(blank=True, help_text='Please enter the date in <b>YYYY-MM-DD</b> format.', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
