# Generated by Django 2.2.4 on 2019-09-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed',
        ),
    ]
