# Generated by Django 2.2.4 on 2019-09-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20190916_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
