# Generated by Django 2.2 on 2019-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
    ]
