# Generated by Django 2.2.4 on 2019-08-21 15:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190502_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
