# Generated by Django 2.2.4 on 2019-08-21 15:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_house_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
